name = "Vaulters Paradise"
author = "Dog"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "693e12adb6887063e405649fb90027d6adc0f726881cac59699b658848420d42"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
