name = "Vaulters Paradise"
author = "Dog"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1b2882bcafb2079649c5596d9aa98a75f1ac68791cdff91c3303567b2519a43"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
