name = "Vaulters Paradise"
author = "Dog"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7369f2a3b31c030d7a56ffd6c2aad9fab34f3bd1759448755d4cf5550f40aea"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
