name = "Vaulters Paradise"
author = "Dog"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f5e56bedfa93cb87ab2bbf60edcc9414f72208c150cb43a5132d4bdc45ec8d4"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
