name = "Vaulters Paradise"
author = "Dog"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bebb5a4d4057f363a0bea5b098b916a461ef911a145b901412cd72cad9f0be67"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
