
#List of curio slot type settings
[[curiosSettings]]
identifier = "head"
visible = true
override = true

[[curiosSettings]]
identifier = "belt"
visible = true
override = true

[[curiosSettings]]
identifier = "back"
visible = true
override = true

[[curiosSettings]]
identifier = "body"
visible = false
override = true

[[curiosSettings]]
identifier = "ring"
visible = false
override = true

[[curiosSettings]]
identifier = "necklace"
visible = true
override = true

[[curiosSettings]]
identifier = "trinket"
priority = 10
size = 1
visible = false
cosmetic = false
icon = "curios:item/empty_cosmetic_slot"

[[curiosSettings]]
identifier = "red_trinket"
priority = 10
size = 1
visible = true
cosmetic = false
icon = "curios:item/empty_cosmetic_slot"

[[curiosSettings]]
identifier = "blue_trinket"
priority = 10
size = 1
visible = true
cosmetic = false
icon = "curios:item/empty_cosmetic_slot"

[[curiosSettings]]
identifier = "tiab"
priority = 9
size = 1
visible = true
cosmetic = false
icon = "curios:item/empty_cosmetic_slot"


[[curiosSettings]]
identifier = "charm"
priority = 9
size = 1
visible = true
cosmetic = false
icon = "curios:item/empty_charm_slot"
override = true

[[curiosSettings]]
identifier = "deck"
priority = 11
size = 1
visible = true
cosmetic = false
icon = "the_vault:gui/slot/curios/deck_slot"

[[curiosSettings]]
identifier = "compass"
priority = 12
size = 1
visible = true
cosmetic = false
icon = "the_vault:gui/slot/curios/vault_compass"

[[curiosSettings]]
identifier = "coin_pouch"
priority = 13
size = 1
visible = true
cosmetic = false
icon = "the_vault:gui/slot/curios/coinpouch"

[[curiosSettings]]
identifier = "shard_pouch"
priority = 14
size = 1
visible = true
cosmetic = false
icon = "the_vault:gui/slot/curios/shard"